### ISSUE TITLE
注册页面输入完信息后点击注册 报错http500

### ISSUE THREAD

**Issue by arthur-wxy** [chaizhidream/examOnline#7]

**Comment by arthur-wxy** [comment]
![screen shot 2018-12-19 at 22 41 21](https://user-images.githubusercontent.com/39916187/50226849-3d25f980-03df-11e9-9c2c-ed520dd75679.png)
这是什么原因啊，怎么解决呀

**Comment by zhangjianagry** [comment]
去db.pro配置文件里面配置数据库
